baseURL: https://www.infopantai.com/
languageCode: id-ID
title: INFOPANTAI
theme: "PaperMod"
paginate: 7
defaultContentLanguage: id
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-F05V2K8VM7

minify:
  disableXML: true
  minifyOutput: true

languages:
    id:
        languageName: "Indonesian"
        weight: 1
        taxonomies:
          category: kategori
          tag: topik
          series: series
        menu:
          main:
            - identifier: disclaimer
              name: Disclaimer
              url: /disclaimer/
              weight: 10
            - identifier: tentang
              name: Tentang
              url: /tentang/
              weight: 20
            - identifier: privacy-policy
              name: Privacy Policy
              url: /privacy-policy/
              weight: 30
            - identifier: kontak
              name: Kontak
              url: /kontak/

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: InfoPantai
  description: "Info pantai di DIY dan penginapan di sekitarnya."
  keywords: [Pantai Jogja, Pantai, Info Wisata]
  author: Admin
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "02 January 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: favicon.ico
    favicon16x16: favicon16x16.png
    favicon32x32: favicon32x32.png
    apple_touch_icon: apple-touch-icon.png
    safari_pinned_tab: safari-pinned-tab.png

   # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Halo! \U0001F44B"
    Content: Selamat datang di InfoPantai.com! Selamat menikmati!

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

permalinks:
  blog: /:filename/
